baseURL: https://start.hbstack.dev/
copyright: Copyright © 2023-{year} [HB Framework](https://hbstack.dev/) and [Hugo Modules](https://hugomods.com/). All Rights Reserved.
title: HB Start Theme

build:
  writeStats: true
